### ISSUE TITLE
下载代码之后，在本地执行 mdbook build --open, 在浏览器访问 http://127.0.0.1:3000 没内容啊

### ISSUE THREAD

**Issue by kotlin2018** [night-cruise/async-rust#3]
下载代码之后，在本地执行 mdbook build --open, 在浏览器访问 http://127.0.0.1:3000 没内容啊
有可能是 `SUMMARY.md` 的原因

**Comment by night-cruise** [comment]
* `mdbook build --open` 之后应该会自动打开浏览器，然后就能看到内容了，这个时候在浏览器访问 http://127.0.0.1:3000 肯定是没有的。如果浏览器没有自动打开，可以在打开 docs 目录的 index.html 文件。
* 也可以使用 `mdbook serve` 命令，然后使用浏览器访问 http://localhost:3000 应该也能看到内容。

**Comment by night-cruise** [comment]
问题应该解决了吧，我把 issue 关了。
